import { prisma } from "@javaquets/database";
import type { AdminCourseDto, AdminQuestDto } from "@javaquets/shared";
import { AppError, NotFoundError } from "../../common/errors/AppError.js";
import { increment } from "../../common/observability/metrics.js";

const courseInclude={modules:{orderBy:{position:"asc" as const},include:{quests:{orderBy:{position:"asc" as const},include:{lessons:{orderBy:{position:"asc" as const}},exercises:{orderBy:{position:"asc" as const},include:{testCases:{orderBy:{position:"asc" as const}}}}}}}}};
const questInclude={module:true,lessons:{orderBy:{position:"asc" as const}},exercises:{orderBy:{position:"asc" as const},include:{testCases:{orderBy:{position:"asc" as const}}}}};
function questDto(q:any):AdminQuestDto{return{id:q.id,moduleId:q.moduleId,slug:q.slug,title:q.title,description:q.description,status:q.status,difficulty:q.difficulty,position:q.position,estimatedMinutes:q.estimatedMinutes,version:q.version,publishedAt:q.publishedAt?.toISOString()??null,lessons:q.lessons.map((l:any)=>({...l,createdAt:undefined,updatedAt:undefined,questId:undefined})),exercises:q.exercises.map((e:any)=>({id:e.id,slug:e.slug,title:e.title,prompt:e.prompt,kind:e.kind,difficulty:e.difficulty,position:e.position,starterCode:e.starterCode,solution:e.solution,executionTimeoutMs:e.executionTimeoutMs,testCases:e.testCases.map((t:any)=>({id:t.id,position:t.position,input:t.input,expectedOutput:t.expectedOutput,isHidden:t.isHidden}))}))};}
function courseDto(c:any):AdminCourseDto{return{id:c.id,slug:c.slug,title:c.title,description:c.description,status:c.status,difficulty:c.difficulty,version:c.version,publishedAt:c.publishedAt?.toISOString()??null,modules:c.modules.map((m:any)=>({id:m.id,courseId:m.courseId,slug:m.slug,title:m.title,description:m.description,position:m.position,quests:m.quests.map(questDto)}))};}
async function audit(adminId:string,action:"CREATE"|"UPDATE"|"PUBLISH"|"ARCHIVE"|"REORDER",entityType:string,entityId:string,entitySlug?:string,metadata?:unknown){await prisma.contentAuditEvent.create({data:{adminId,action,entityType,entityId,entitySlug,metadata:metadata as any}});}
async function course(id:string){const value=await prisma.course.findUnique({where:{id},include:courseInclude});if(!value)throw new NotFoundError("COURSE_NOT_FOUND","Course not found");return value;}
async function quest(id:string){const value=await prisma.quest.findUnique({where:{id},include:questInclude});if(!value)throw new NotFoundError("QUEST_NOT_FOUND","Quest not found");return value;}
export async function listAdminCourses(){return(await prisma.course.findMany({orderBy:{updatedAt:"desc"},include:courseInclude})).map(courseDto);}
export async function getAdminCourse(id:string){return courseDto(await course(id));}
export async function getAdminQuest(id:string){return questDto(await quest(id));}
export async function createCourse(adminId:string,data:any){const created=await prisma.course.create({data:{...data,updatedById:adminId},include:courseInclude});await audit(adminId,"CREATE","COURSE",created.id,created.slug);return courseDto(created);}
export async function updateCourse(adminId:string,id:string,data:any){const updated=await prisma.course.update({where:{id},data:{...data,version:{increment:1},updatedById:adminId},include:courseInclude});await audit(adminId,"UPDATE","COURSE",id,updated.slug);return courseDto(updated);}
export async function addModule(adminId:string,courseId:string,data:any){await course(courseId);const created=await prisma.courseModule.create({data:{...data,courseId}});await audit(adminId,"CREATE","MODULE",created.id,created.slug,{courseId});return created;}
export async function addQuest(adminId:string,moduleId:string,data:any){const module=await prisma.courseModule.findUnique({where:{id:moduleId}});if(!module)throw new NotFoundError("MODULE_NOT_FOUND","Module not found");const created=await prisma.quest.create({data:{...data,moduleId,updatedById:adminId},include:questInclude});await audit(adminId,"CREATE","QUEST",created.id,created.slug,{moduleId});return questDto(created);}
export async function updateQuest(adminId:string,id:string,data:any){const updated=await prisma.quest.update({where:{id},data:{...data,version:{increment:1},updatedById:adminId},include:questInclude});await audit(adminId,"UPDATE","QUEST",id,updated.slug);return questDto(updated);}
export async function addLesson(adminId:string,questId:string,data:any){await quest(questId);const created=await prisma.lesson.create({data:{...data,questId}});await prisma.quest.update({where:{id:questId},data:{version:{increment:1},updatedById:adminId}});await audit(adminId,"CREATE","LESSON",created.id,created.slug,{questId});return created;}
export async function updateLesson(adminId:string,id:string,data:any){const updated=await prisma.lesson.update({where:{id},data});await prisma.quest.update({where:{id:updated.questId},data:{version:{increment:1},updatedById:adminId}});await audit(adminId,"UPDATE","LESSON",id,updated.slug);return updated;}
export async function addExercise(adminId:string,questId:string,data:any){await quest(questId);const{testCases,...exercise}=data;const created=await prisma.exercise.create({data:{...exercise,questId,testCases:{create:testCases}},include:{testCases:{orderBy:{position:"asc"}}}});await prisma.quest.update({where:{id:questId},data:{version:{increment:1},updatedById:adminId}});await audit(adminId,"CREATE","EXERCISE",created.id,created.slug,{questId});return created;}
export async function updateExercise(adminId:string,id:string,data:any){const current=await prisma.exercise.findUnique({where:{id}});if(!current)throw new NotFoundError("EXERCISE_NOT_FOUND","Exercise not found");const{testCases,...exercise}=data;const updated=await prisma.$transaction(async tx=>{await tx.testCase.deleteMany({where:{exerciseId:id}});return tx.exercise.update({where:{id},data:{...exercise,testCases:{create:testCases}},include:{testCases:{orderBy:{position:"asc"}}}})});await prisma.quest.update({where:{id:current.questId},data:{version:{increment:1},updatedById:adminId}});await audit(adminId,"UPDATE","EXERCISE",id,updated.slug);return updated;}
function contiguous(values:number[]){return values.every((value,index)=>value===index+1);}
function validateQuestForPublish(q:Awaited<ReturnType<typeof quest>>){const issues:string[]=[];if(!q.lessons.length&&!q.exercises.length)issues.push("Quest must contain at least one lesson or exercise");if(!contiguous(q.lessons.map(l=>l.position)))issues.push("Lesson positions must be contiguous from 1");if(!contiguous(q.exercises.map(e=>e.position)))issues.push("Exercise positions must be contiguous from 1");for(const e of q.exercises){if(e.kind==="CODE"){if(!e.starterCode?.trim())issues.push(`${e.slug}: starter code is required`);if(!e.solution?.trim())issues.push(`${e.slug}: solution is required`);if(!e.testCases.length)issues.push(`${e.slug}: at least one test case is required`);if(!e.testCases.some(t=>!t.isHidden))issues.push(`${e.slug}: at least one public test is required`);if(!e.testCases.some(t=>t.isHidden))issues.push(`${e.slug}: at least one hidden test is required`);if(!contiguous(e.testCases.map(t=>t.position)))issues.push(`${e.slug}: test positions must be contiguous from 1`);}}if(issues.length)throw new AppError("CONTENT_PUBLISH_VALIDATION_FAILED","Quest cannot be published",422,{issues});}
export async function publishQuest(adminId:string,id:string){const q=await quest(id);validateQuestForPublish(q);const updated=await prisma.quest.update({where:{id},data:{status:"PUBLISHED",publishedAt:new Date(),version:{increment:1},updatedById:adminId},include:questInclude});await audit(adminId,"PUBLISH","QUEST",id,updated.slug,{version:updated.version});increment("javaquets_admin_publish_total",{entity:"quest"});return questDto(updated);}
export async function publishCourse(adminId:string,id:string){const c=await course(id);if(!c.modules.length)throw new AppError("CONTENT_PUBLISH_VALIDATION_FAILED","Course must contain a module",422);if(!contiguous(c.modules.map(m=>m.position)))throw new AppError("CONTENT_PUBLISH_VALIDATION_FAILED","Module positions must be contiguous from 1",422);for(const m of c.modules){if(!contiguous(m.quests.map(q=>q.position)))throw new AppError("CONTENT_PUBLISH_VALIDATION_FAILED",`${m.slug} quest positions must be contiguous from 1`,422);for(const q of m.quests.filter(q=>q.status==="PUBLISHED"))validateQuestForPublish(q as any);}if(!c.modules.some(m=>m.quests.some(q=>q.status==="PUBLISHED")))throw new AppError("CONTENT_PUBLISH_VALIDATION_FAILED","Course needs at least one published quest",422);const updated=await prisma.course.update({where:{id},data:{status:"PUBLISHED",publishedAt:new Date(),version:{increment:1},updatedById:adminId},include:courseInclude});await audit(adminId,"PUBLISH","COURSE",id,updated.slug,{version:updated.version});increment("javaquets_admin_publish_total",{entity:"course"});return courseDto(updated);}
export async function archive(adminId:string,type:"course"|"quest",id:string){if(type==="course"){const updated=await prisma.course.update({where:{id},data:{status:"ARCHIVED",version:{increment:1},updatedById:adminId},include:courseInclude});await audit(adminId,"ARCHIVE","COURSE",id,updated.slug);return courseDto(updated);}const updated=await prisma.quest.update({where:{id},data:{status:"ARCHIVED",version:{increment:1},updatedById:adminId},include:questInclude});await audit(adminId,"ARCHIVE","QUEST",id,updated.slug);return questDto(updated);}
export async function reorder(adminId:string,type:"modules"|"quests",parentId:string,ids:string[]){const existing=type==="modules"?await prisma.courseModule.findMany({where:{courseId:parentId},select:{id:true}}):await prisma.quest.findMany({where:{moduleId:parentId},select:{id:true}});if(existing.length!==ids.length||existing.some(x=>!ids.includes(x.id)))throw new AppError("INVALID_ORDER","Order must contain every child exactly once",422);await prisma.$transaction(async tx=>{for(let index=0;index<ids.length;index++){if(type==="modules")await tx.courseModule.update({where:{id:ids[index]},data:{position:-(index+1)}});else await tx.quest.update({where:{id:ids[index]},data:{position:-(index+1)}});}for(let index=0;index<ids.length;index++){if(type==="modules")await tx.courseModule.update({where:{id:ids[index]},data:{position:index+1}});else await tx.quest.update({where:{id:ids[index]},data:{position:index+1}});}});await audit(adminId,"REORDER",type.toUpperCase(),parentId,undefined,{ids});}
export async function listAudit(){return(await prisma.contentAuditEvent.findMany({take:100,orderBy:{createdAt:"desc"},include:{admin:{select:{email:true}}}})).map(e=>({id:e.id,action:e.action,entityType:e.entityType,entityId:e.entityId,entitySlug:e.entitySlug,adminEmail:e.admin.email,metadata:e.metadata,createdAt:e.createdAt.toISOString()}));}
