import { Router } from "express";
import { requireAdmin } from "../../common/auth/adminContext.js";
import * as controller from "./admin.controller.js";
export const adminRouter=Router();
adminRouter.use("/admin",requireAdmin);
adminRouter.get("/admin/courses",controller.listCourses);
adminRouter.post("/admin/courses",controller.createCourse);
adminRouter.get("/admin/courses/:id",controller.getCourse);
adminRouter.patch("/admin/courses/:id",controller.updateCourse);
adminRouter.post("/admin/courses/:id/modules",controller.addModule);
adminRouter.post("/admin/courses/:id/publish",controller.publishCourse);
adminRouter.post("/admin/courses/:id/archive",controller.archiveCourse);
adminRouter.put("/admin/courses/:id/module-order",controller.reorderModules);
adminRouter.post("/admin/modules/:id/quests",controller.addQuest);
adminRouter.put("/admin/modules/:id/quest-order",controller.reorderQuests);
adminRouter.patch("/admin/quests/:id",controller.updateQuest);
adminRouter.get("/admin/quests/:id",controller.getQuest);
adminRouter.post("/admin/quests/:id/lessons",controller.addLesson);
adminRouter.post("/admin/quests/:id/exercises",controller.addExercise);
adminRouter.post("/admin/quests/:id/publish",controller.publishQuest);
adminRouter.post("/admin/quests/:id/archive",controller.archiveQuest);
adminRouter.patch("/admin/lessons/:id",controller.updateLesson);
adminRouter.put("/admin/exercises/:id",controller.updateExercise);
adminRouter.get("/admin/audit",controller.audit);
