import type { NextFunction, Request, Response } from "express";
import { adminCourseSchema, adminExerciseSchema, adminLessonSchema, adminModuleSchema, adminQuestSchema, reorderSchema } from "@javaquets/validation";
import { getLearnerId } from "../../common/auth/learnerContext.js";
import * as service from "./admin.service.js";
const handle=(fn:(req:Request,res:Response)=>Promise<void>)=>(req:Request,res:Response,next:NextFunction)=>fn(req,res).catch(next);
const id=(req:Request)=>req.params.id!;
export const listCourses=handle(async(_req,res)=>{res.json({items:await service.listAdminCourses()})});
export const getCourse=handle(async(req,res)=>{res.json(await service.getAdminCourse(id(req)))});
export const getQuest=handle(async(req,res)=>{res.json(await service.getAdminQuest(id(req)))});
export const createCourse=handle(async(req,res)=>{res.status(201).json(await service.createCourse(getLearnerId(req),adminCourseSchema.parse(req.body)))});
export const updateCourse=handle(async(req,res)=>{res.json(await service.updateCourse(getLearnerId(req),id(req),adminCourseSchema.partial().parse(req.body)))});
export const addModule=handle(async(req,res)=>{res.status(201).json(await service.addModule(getLearnerId(req),id(req),adminModuleSchema.parse(req.body)))});
export const addQuest=handle(async(req,res)=>{res.status(201).json(await service.addQuest(getLearnerId(req),id(req),adminQuestSchema.parse(req.body)))});
export const updateQuest=handle(async(req,res)=>{res.json(await service.updateQuest(getLearnerId(req),id(req),adminQuestSchema.partial().parse(req.body)))});
export const addLesson=handle(async(req,res)=>{res.status(201).json(await service.addLesson(getLearnerId(req),id(req),adminLessonSchema.parse(req.body)))});
export const updateLesson=handle(async(req,res)=>{res.json(await service.updateLesson(getLearnerId(req),id(req),adminLessonSchema.partial().parse(req.body)))});
export const addExercise=handle(async(req,res)=>{res.status(201).json(await service.addExercise(getLearnerId(req),id(req),adminExerciseSchema.parse(req.body)))});
export const updateExercise=handle(async(req,res)=>{res.json(await service.updateExercise(getLearnerId(req),id(req),adminExerciseSchema.parse(req.body)))});
export const publishQuest=handle(async(req,res)=>{res.json(await service.publishQuest(getLearnerId(req),id(req)))});
export const publishCourse=handle(async(req,res)=>{res.json(await service.publishCourse(getLearnerId(req),id(req)))});
export const archiveCourse=handle(async(req,res)=>{res.json(await service.archive(getLearnerId(req),"course",id(req)))});
export const archiveQuest=handle(async(req,res)=>{res.json(await service.archive(getLearnerId(req),"quest",id(req)))});
export const reorderModules=handle(async(req,res)=>{await service.reorder(getLearnerId(req),"modules",id(req),reorderSchema.parse(req.body).ids);res.status(204).send()});
export const reorderQuests=handle(async(req,res)=>{await service.reorder(getLearnerId(req),"quests",id(req),reorderSchema.parse(req.body).ids);res.status(204).send()});
export const audit=handle(async(_req,res)=>{res.json({items:await service.listAudit()})});
