import type { AdminCourseDto, AdminQuestDto, ContentAuditEventDto } from "@javaquets/shared";
import { apiFetch } from "@/lib/api";
export const listAdminCourses=async()=>(await apiFetch<{items:AdminCourseDto[]}>("/admin/courses")).items;
export const getAdminCourse=(id:string)=>apiFetch<AdminCourseDto>(`/admin/courses/${id}`);
export const getAdminQuest=(id:string)=>apiFetch<AdminQuestDto>(`/admin/quests/${id}`);
export const createAdminCourse=(data:unknown)=>apiFetch<AdminCourseDto>("/admin/courses",{method:"POST",body:JSON.stringify(data)});
export const updateAdminCourse=(id:string,data:unknown)=>apiFetch<AdminCourseDto>(`/admin/courses/${id}`,{method:"PATCH",body:JSON.stringify(data)});
export const addAdminModule=(id:string,data:unknown)=>apiFetch(`/admin/courses/${id}/modules`,{method:"POST",body:JSON.stringify(data)});
export const addAdminQuest=(id:string,data:unknown)=>apiFetch<AdminQuestDto>(`/admin/modules/${id}/quests`,{method:"POST",body:JSON.stringify(data)});
export const updateAdminQuest=(id:string,data:unknown)=>apiFetch<AdminQuestDto>(`/admin/quests/${id}`,{method:"PATCH",body:JSON.stringify(data)});
export const addAdminLesson=(id:string,data:unknown)=>apiFetch(`/admin/quests/${id}/lessons`,{method:"POST",body:JSON.stringify(data)});
export const addAdminExercise=(id:string,data:unknown)=>apiFetch(`/admin/quests/${id}/exercises`,{method:"POST",body:JSON.stringify(data)});
export const publishAdminQuest=(id:string)=>apiFetch<AdminQuestDto>(`/admin/quests/${id}/publish`,{method:"POST"});
export const publishAdminCourse=(id:string)=>apiFetch<AdminCourseDto>(`/admin/courses/${id}/publish`,{method:"POST"});
export const archiveAdminCourse=(id:string)=>apiFetch<AdminCourseDto>(`/admin/courses/${id}/archive`,{method:"POST"});
export const archiveAdminQuest=(id:string)=>apiFetch<AdminQuestDto>(`/admin/quests/${id}/archive`,{method:"POST"});
export const reorderModules=(id:string,ids:string[])=>apiFetch<void>(`/admin/courses/${id}/module-order`,{method:"PUT",body:JSON.stringify({ids})});
export const reorderQuests=(id:string,ids:string[])=>apiFetch<void>(`/admin/modules/${id}/quest-order`,{method:"PUT",body:JSON.stringify({ids})});
export const listAudit=async()=>(await apiFetch<{items:ContentAuditEventDto[]}>("/admin/audit")).items;
