"use client";
import { useCallback, useEffect, useState } from "react";
import type { GamificationDto } from "@javaquets/shared";
import { getGamification } from "@/services/gamification";
import { ProgressBar } from "@/components/progress-bar";
import { ErrorState, LoadingState } from "@/components/states";
export function GamificationSummary() {
  const [data,setData]=useState<GamificationDto|null>(null); const [error,setError]=useState("");
  const load=useCallback(()=>{setError("");getGamification().then(setData).catch(e=>setError(e instanceof Error?e.message:"Could not load learner stats"))},[]); useEffect(load,[load]);
  if(error)return <ErrorState message={error} retry={load}/>; if(!data)return <LoadingState label="Loading XP and achievements…"/>;
  return <section className="mt-8"><div className="grid gap-4 sm:grid-cols-3"><div className="card bg-gradient-to-br from-amber-400 to-orange-500 !text-slate-950"><p className="text-sm font-bold opacity-70">Level</p><p className="mt-2 text-4xl font-black">{data.level}</p><div className="mt-5"><ProgressBar value={data.nextLevelXp?data.currentLevelXp/data.nextLevelXp*100:0} label={`${data.currentLevelXp}/${data.nextLevelXp} XP`}/></div></div><div className="card"><p className="text-sm text-slate-400">Total XP</p><p className="mt-2 text-4xl font-black text-amber-400">{data.totalXp}</p><p className="mt-4 text-sm text-slate-500">Complete learning milestones to earn XP.</p></div><div className="card"><p className="text-sm text-slate-400">Learning streak</p><p className="mt-2 text-4xl font-black">🔥 {data.currentStreak}</p><p className="mt-4 text-sm text-slate-500">Longest: {data.longestStreak} days</p></div></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><div><h2 className="text-2xl font-bold">Achievements</h2><div className="mt-4 grid gap-3">{data.achievements.length?data.achievements.map(a=><div className="card flex items-center gap-4" key={a.slug}><span className="flex h-12 w-12 items-center justify-center rounded-full bg-amber-400 text-xl text-slate-950">★</span><div><p className="font-bold">{a.title}</p><p className="text-sm text-slate-400">{a.description}</p></div></div>):<div className="card text-sm text-slate-400">Complete your first exercise to unlock an achievement.</div>}</div></div><div><h2 className="text-2xl font-bold">Recent XP</h2><div className="card mt-4 divide-y divide-slate-800">{data.recentXp.length?data.recentXp.map(e=><div className="flex justify-between py-3 first:pt-0 last:pb-0" key={e.id}><div><p className="font-semibold">{e.reason}</p><p className="text-xs text-slate-500">{new Date(e.createdAt).toLocaleDateString()}</p></div><span className="font-bold text-amber-400">+{e.amount} XP</span></div>):<p className="text-sm text-slate-400">Your XP history will appear here.</p>}</div></div></div></section>;
}
