import { execFile, spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
export type Result={exitCode:number|null;stdout:string;stderr:string;runtimeMs:number;timedOut:boolean;outputLimitExceeded:boolean};
const image=process.env.JAVA_RUNNER_IMAGE??"javaquets-java-runner:local";const maxConcurrency=numberEnv("RUNNER_MAX_CONCURRENCY",2,1,32);const maxQueue=numberEnv("RUNNER_MAX_QUEUE",8,0,100);const maxOutput=numberEnv("RUNNER_MAX_OUTPUT_BYTES",16384,1024,1048576);let active=0;const queue:Array<()=>void>=[];
function numberEnv(name:string,fallback:number,min:number,max:number){const value=Number(process.env[name]??fallback);if(!Number.isInteger(value)||value<min||value>max)throw new Error(`${name} is invalid`);return value}
async function acquire(){if(active>=maxConcurrency){if(queue.length>=maxQueue)throw Object.assign(new Error("Execution queue is full"),{statusCode:503,code:"RUNNER_BUSY"});await new Promise<void>(resolve=>queue.push(resolve))}active++;let done=false;return()=>{if(done)return;done=true;active--;queue.shift()?.()}}
function cleanupContainer(name:string){return new Promise<void>(resolve=>execFile("docker",["rm","-f",name],{timeout:3000,windowsHide:true},()=>resolve()))}
export function stats(){return{active,queued:queue.length,maxConcurrency,maxQueue}}
export function checkDocker(){return new Promise<boolean>(resolve=>execFile("docker",["image","inspect",image],{timeout:3000,windowsHide:true},error=>resolve(!error)))}
export async function execute(sourceCode:string,stdin:string,timeoutMs:number):Promise<Result>{const release=await acquire();const name=`javaquets-${randomUUID()}`;let dir:string|undefined;try{dir=await mkdtemp(join(tmpdir(),"javaquets-worker-"));await writeFile(join(dir,"Main.java"),sourceCode,"utf8");const started=Date.now();return await new Promise((resolve,reject)=>{const child=spawn("docker",["run","--name",name,"--rm","--network","none","--memory","128m","--cpus","0.5","--pids-limit","64","--read-only","--tmpfs","/tmp:rw,noexec,nosuid,size=16m","--security-opt","no-new-privileges","--cap-drop","ALL","-v",`${dir}:/workspace:rw`,`-w`,`/workspace`,image,"sh","-lc",`javac Main.java && timeout ${Math.max(1,Math.ceil(timeoutMs/1000))}s java -Xmx64m Main`],{stdio:["pipe","pipe","pipe"],windowsHide:true});let stdout="",stderr="",timedOut=false,outputLimitExceeded=false,settled=false;const kill=()=>{void cleanupContainer(name);child.kill("SIGKILL")};const timer=setTimeout(()=>{timedOut=true;kill()},timeoutMs+5000);const append=(target:"out"|"err",chunk:Buffer)=>{if(target==="out")stdout+=chunk.toString();else stderr+=chunk.toString();if(Buffer.byteLength(stdout)+Buffer.byteLength(stderr)>maxOutput){outputLimitExceeded=true;kill()}};child.stdout.on("data",(b:Buffer)=>append("out",b));child.stderr.on("data",(b:Buffer)=>append("err",b));child.on("error",error=>{if(!settled){settled=true;clearTimeout(timer);reject(error)}});child.on("close",code=>{if(settled)return;settled=true;clearTimeout(timer);resolve({exitCode:code,stdout:stdout.slice(0,maxOutput),stderr:stderr.slice(0,maxOutput),runtimeMs:Date.now()-started,timedOut,outputLimitExceeded})});child.stdin.end(stdin)})}finally{await cleanupContainer(name);if(dir)await rm(dir,{recursive:true,force:true});release()}}
